// Auth action types
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_LOADED = 'USER_LOADED';
export const LOADING_USER = 'LOADING_USER';

// Class action types
export const GET_CLASSES_REQUEST = 'GET_CLASSES_REQUEST';
export const GET_CLASSES_SUCCESS = 'GET_CLASSES_SUCCESS';
export const GET_CLASSES_FAIL = 'GET_CLASSES_FAIL';

export const GET_CLASS_REQUEST = 'GET_CLASS_REQUEST';
export const GET_CLASS_SUCCESS = 'GET_CLASS_SUCCESS';
export const GET_CLASS_FAIL = 'GET_CLASS_FAIL';

export const CREATE_CLASS_REQUEST = 'CREATE_CLASS_REQUEST';
export const CREATE_CLASS_SUCCESS = 'CREATE_CLASS_SUCCESS';
export const CREATE_CLASS_FAIL = 'CREATE_CLASS_FAIL';

export const UPDATE_CLASS_REQUEST = 'UPDATE_CLASS_REQUEST';
export const UPDATE_CLASS_SUCCESS = 'UPDATE_CLASS_SUCCESS';
export const UPDATE_CLASS_FAIL = 'UPDATE_CLASS_FAIL';

export const DELETE_CLASS_REQUEST = 'DELETE_CLASS_REQUEST';
export const DELETE_CLASS_SUCCESS = 'DELETE_CLASS_SUCCESS';
export const DELETE_CLASS_FAIL = 'DELETE_CLASS_FAIL';

export const ENROLL_STUDENT_REQUEST = 'ENROLL_STUDENT_REQUEST';
export const ENROLL_STUDENT_SUCCESS = 'ENROLL_STUDENT_SUCCESS';
export const ENROLL_STUDENT_FAIL = 'ENROLL_STUDENT_FAIL';

export const REMOVE_STUDENT_REQUEST = 'REMOVE_STUDENT_REQUEST';
export const REMOVE_STUDENT_SUCCESS = 'REMOVE_STUDENT_SUCCESS';
export const REMOVE_STUDENT_FAIL = 'REMOVE_STUDENT_FAIL';

// Assignment action types
export const GET_ASSIGNMENTS_REQUEST = 'GET_ASSIGNMENTS_REQUEST';
export const GET_ASSIGNMENTS_SUCCESS = 'GET_ASSIGNMENTS_SUCCESS';
export const GET_ASSIGNMENTS_FAIL = 'GET_ASSIGNMENTS_FAIL';

export const GET_ASSIGNMENT_REQUEST = 'GET_ASSIGNMENT_REQUEST';
export const GET_ASSIGNMENT_SUCCESS = 'GET_ASSIGNMENT_SUCCESS';
export const GET_ASSIGNMENT_FAIL = 'GET_ASSIGNMENT_FAIL';

export const CREATE_ASSIGNMENT_REQUEST = 'CREATE_ASSIGNMENT_REQUEST';
export const CREATE_ASSIGNMENT_SUCCESS = 'CREATE_ASSIGNMENT_SUCCESS';
export const CREATE_ASSIGNMENT_FAIL = 'CREATE_ASSIGNMENT_FAIL';

export const UPDATE_ASSIGNMENT_REQUEST = 'UPDATE_ASSIGNMENT_REQUEST';
export const UPDATE_ASSIGNMENT_SUCCESS = 'UPDATE_ASSIGNMENT_SUCCESS';
export const UPDATE_ASSIGNMENT_FAIL = 'UPDATE_ASSIGNMENT_FAIL';

export const DELETE_ASSIGNMENT_REQUEST = 'DELETE_ASSIGNMENT_REQUEST';
export const DELETE_ASSIGNMENT_SUCCESS = 'DELETE_ASSIGNMENT_SUCCESS';
export const DELETE_ASSIGNMENT_FAIL = 'DELETE_ASSIGNMENT_FAIL';

export const SUBMIT_ASSIGNMENT_REQUEST = 'SUBMIT_ASSIGNMENT_REQUEST';
export const SUBMIT_ASSIGNMENT_SUCCESS = 'SUBMIT_ASSIGNMENT_SUCCESS';
export const SUBMIT_ASSIGNMENT_FAIL = 'SUBMIT_ASSIGNMENT_FAIL';

export const GRADE_ASSIGNMENT_REQUEST = 'GRADE_ASSIGNMENT_REQUEST';
export const GRADE_ASSIGNMENT_SUCCESS = 'GRADE_ASSIGNMENT_SUCCESS';
export const GRADE_ASSIGNMENT_FAIL = 'GRADE_ASSIGNMENT_FAIL';

// Schedule action types
export const GET_SCHEDULES_REQUEST = 'GET_SCHEDULES_REQUEST';
export const GET_SCHEDULES_SUCCESS = 'GET_SCHEDULES_SUCCESS';
export const GET_SCHEDULES_FAIL = 'GET_SCHEDULES_FAIL';

export const GET_SCHEDULE_REQUEST = 'GET_SCHEDULE_REQUEST';
export const GET_SCHEDULE_SUCCESS = 'GET_SCHEDULE_SUCCESS';
export const GET_SCHEDULE_FAIL = 'GET_SCHEDULE_FAIL';

export const CREATE_SCHEDULE_REQUEST = 'CREATE_SCHEDULE_REQUEST';
export const CREATE_SCHEDULE_SUCCESS = 'CREATE_SCHEDULE_SUCCESS';
export const CREATE_SCHEDULE_FAIL = 'CREATE_SCHEDULE_FAIL';

export const UPDATE_SCHEDULE_REQUEST = 'UPDATE_SCHEDULE_REQUEST';
export const UPDATE_SCHEDULE_SUCCESS = 'UPDATE_SCHEDULE_SUCCESS';
export const UPDATE_SCHEDULE_FAIL = 'UPDATE_SCHEDULE_FAIL';

export const DELETE_SCHEDULE_REQUEST = 'DELETE_SCHEDULE_REQUEST';
export const DELETE_SCHEDULE_SUCCESS = 'DELETE_SCHEDULE_SUCCESS';
export const DELETE_SCHEDULE_FAIL = 'DELETE_SCHEDULE_FAIL';

// Study log action types
export const GET_STUDY_LOGS_REQUEST = 'GET_STUDY_LOGS_REQUEST';
export const GET_STUDY_LOGS_SUCCESS = 'GET_STUDY_LOGS_SUCCESS';
export const GET_STUDY_LOGS_FAIL = 'GET_STUDY_LOGS_FAIL';

export const GET_STUDY_LOG_REQUEST = 'GET_STUDY_LOG_REQUEST';
export const GET_STUDY_LOG_SUCCESS = 'GET_STUDY_LOG_SUCCESS';
export const GET_STUDY_LOG_FAIL = 'GET_STUDY_LOG_FAIL';

export const CREATE_STUDY_LOG_REQUEST = 'CREATE_STUDY_LOG_REQUEST';
export const CREATE_STUDY_LOG_SUCCESS = 'CREATE_STUDY_LOG_SUCCESS';
export const CREATE_STUDY_LOG_FAIL = 'CREATE_STUDY_LOG_FAIL';

export const UPDATE_STUDY_LOG_REQUEST = 'UPDATE_STUDY_LOG_REQUEST';
export const UPDATE_STUDY_LOG_SUCCESS = 'UPDATE_STUDY_LOG_SUCCESS';
export const UPDATE_STUDY_LOG_FAIL = 'UPDATE_STUDY_LOG_FAIL';

export const DELETE_STUDY_LOG_REQUEST = 'DELETE_STUDY_LOG_REQUEST';
export const DELETE_STUDY_LOG_SUCCESS = 'DELETE_STUDY_LOG_SUCCESS';
export const DELETE_STUDY_LOG_FAIL = 'DELETE_STUDY_LOG_FAIL';