// Alert Types
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Auth Types
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// Class Types
export const GET_CLASSES = 'GET_CLASSES';
export const GET_CLASS = 'GET_CLASS';
export const CLASS_ERROR = 'CLASS_ERROR';
export const CREATE_CLASS = 'CREATE_CLASS';
export const UPDATE_CLASS = 'UPDATE_CLASS';
export const DELETE_CLASS = 'DELETE_CLASS';

export const GET_CLASSES_REQUEST = 'GET_CLASSES_REQUEST';
export const GET_CLASSES_SUCCESS = 'GET_CLASSES_SUCCESS';
export const GET_CLASSES_FAIL = 'GET_CLASSES_FAIL';

export const GET_CLASS_REQUEST = 'GET_CLASS_REQUEST';
export const GET_CLASS_SUCCESS = 'GET_CLASS_SUCCESS';
export const GET_CLASS_FAIL = 'GET_CLASS_FAIL';

export const CREATE_CLASS_REQUEST = 'CREATE_CLASS_REQUEST';
export const CREATE_CLASS_SUCCESS = 'CREATE_CLASS_SUCCESS';
export const CREATE_CLASS_FAIL = 'CREATE_CLASS_FAIL';

export const UPDATE_CLASS_REQUEST = 'UPDATE_CLASS_REQUEST';
export const UPDATE_CLASS_SUCCESS = 'UPDATE_CLASS_SUCCESS';
export const UPDATE_CLASS_FAIL = 'UPDATE_CLASS_FAIL';

export const DELETE_CLASS_REQUEST = 'DELETE_CLASS_REQUEST';
export const DELETE_CLASS_SUCCESS = 'DELETE_CLASS_SUCCESS';
export const DELETE_CLASS_FAIL = 'DELETE_CLASS_FAIL';

// Study Log Types
export const GET_STUDY_LOGS_REQUEST = 'GET_STUDY_LOGS_REQUEST';
export const GET_STUDY_LOGS_SUCCESS = 'GET_STUDY_LOGS_SUCCESS';
export const GET_STUDY_LOGS_FAIL = 'GET_STUDY_LOGS_FAIL';
export const CREATE_STUDY_LOG_REQUEST = 'CREATE_STUDY_LOG_REQUEST';
export const CREATE_STUDY_LOG_SUCCESS = 'CREATE_STUDY_LOG_SUCCESS';
export const CREATE_STUDY_LOG_FAIL = 'CREATE_STUDY_LOG_FAIL';
export const UPDATE_STUDY_LOG_REQUEST = 'UPDATE_STUDY_LOG_REQUEST';
export const UPDATE_STUDY_LOG_SUCCESS = 'UPDATE_STUDY_LOG_SUCCESS';
export const UPDATE_STUDY_LOG_FAIL = 'UPDATE_STUDY_LOG_FAIL';
export const DELETE_STUDY_LOG_REQUEST = 'DELETE_STUDY_LOG_REQUEST';
export const DELETE_STUDY_LOG_SUCCESS = 'DELETE_STUDY_LOG_SUCCESS';
export const DELETE_STUDY_LOG_FAIL = 'DELETE_STUDY_LOG_FAIL';

// Schedule Types
export const GET_SCHEDULES_REQUEST = 'GET_SCHEDULES_REQUEST';
export const GET_SCHEDULES_SUCCESS = 'GET_SCHEDULES_SUCCESS';
export const GET_SCHEDULES_FAIL = 'GET_SCHEDULES_FAIL';
export const CREATE_SCHEDULE_REQUEST = 'CREATE_SCHEDULE_REQUEST';
export const CREATE_SCHEDULE_SUCCESS = 'CREATE_SCHEDULE_SUCCESS';
export const CREATE_SCHEDULE_FAIL = 'CREATE_SCHEDULE_FAIL';
export const UPDATE_SCHEDULE_REQUEST = 'UPDATE_SCHEDULE_REQUEST';
export const UPDATE_SCHEDULE_SUCCESS = 'UPDATE_SCHEDULE_SUCCESS';
export const UPDATE_SCHEDULE_FAIL = 'UPDATE_SCHEDULE_FAIL';
export const DELETE_SCHEDULE_REQUEST = 'DELETE_SCHEDULE_REQUEST';
export const DELETE_SCHEDULE_SUCCESS = 'DELETE_SCHEDULE_SUCCESS';
export const DELETE_SCHEDULE_FAIL = 'DELETE_SCHEDULE_FAIL'; 